services:
  eladmin:
    build:
      context: .
      dockerfile: Dockerfile
    # image: test
    ports:
      - 8000:8000
    environment:
      DB_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
  mysql:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: eladmin
    volumes:
      - ./sql/eladmin.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/3306"]
      interval: 3s
      timeout: 60s
      retries: 10
      start_period: 3s
